<?php echo $this->doctype(); ?>

<?php
$route = $this->getHelperPluginManager()->getServiceLocator()->get('request')->getUri()->getPath(); 
$isAdmin = false;

$isConteudo = false;

if (strpos($route, 'admin') !== false) {
    $isAdmin = true;
}

if (strpos($route, 'conteudo') !== false) {
    $isConteudo = true;
}

?>

<?php
    header('Access-Control-Allow-Origin: *');
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Content-Type, Content-Range, Content-Disposition, Content-Description');
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Futura União - Consultoria de Seguros'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicosadn.ico'))
                        ->prependStylesheet($this->basePath() . '/css/app.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath() . '/js/plugins/blockui-master/jquery.blockUI.js')
            
            ->appendFile($this->basePath() . '/bower_components/angular/angular.js')
            ->appendFile($this->basePath() . '/bower_components/angular-route/angular-route.js')
            ->appendFile($this->basePath() . '/bower_components/angular-resource/angular-resource.js')
            ->appendFile($this->basePath() . '/js/plugins/ng-table.js')
            ->appendFile($this->basePath() . '/js/plugins/jquery.nestedAccordion.js')
            ->appendFile($this->basePath() . '/js/app/dirPagination.js')
            ->appendFile($this->basePath() . '/js/app/CmsApp.js')
            ->appendFile($this->basePath() . '/js/app/Services.js')
            ->appendFile($this->basePath() . '/js/app/Directives.js')
            ->appendFile($this->basePath() . '/js/app/Controllers.js')
            ->appendFile($this->basePath() . '/js/html5.image.preview.min.js')
            ->prependFile($this->basePath() . '/bower_components/foundation/js/foundation.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            
        ; ?>
    </head>
    <body ng-app='CmsApp'>
      <div ng-controller="RouteCtrl">
        
        

        <header id="navbar-menu-principal" class="fixed">
            <nav class="top-bar" data-topbar role="navigation">
              <!-- Title -->
              <ul class="title-area">
                <li>
                  <a href="/" target="_self"><div id="logo_empresa"></div></a>
                </li>

                <!-- Mobile Menu Toggle -->
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
              </ul>

              <!-- Top Bar Section -->
              <section class="top-bar-section">

                <!-- Top Bar Left Nav Elements -->
                <ul class="left">

                  <!-- Button -->
                  <li class="has-form show-for-large-up">
                    <?php 

                    if ($this->UserIdentity('CmsUser')):
                      $hour =  date('H');
                      $comprimento = 'Bom dia, ';

                      if ($hour > 11) {
                        $comprimento = 'Boa tarde, ';
                      } elseif ($hour > 17) {
                        $comprimento = 'Boa noite, ';
                      }
                      $nome = $this->UserIdentity("CmsUser")->getNome();
                      $etc = "";

                      if (strlen($nome) > 20) {
                        $etc = "...";
                      }

                      echo '<a href="/admin" class="button default-btn-cms btn-cms"  target="_self"><span class="icon-unlocked"></span> ', $comprimento, substr($nome, 0, 20), $etc,'</a>';
                    else:
                      echo '<a href="/admin" class="button default-btn-cms  btn-cms"  target="_self"><span class="icon-lock2"></span> Acesso Restrito</a>';
                    endif;
                    ?>
                    
                  </li>
                  <?php if ($this->UserIdentity('CmsUser')): ?>
                  <li class="has-form show-for-large-up">
                    <a href="/auth/logout" class="button quit-btn-cms btn-cms" target="_self"><span class="icon-exit"></span>&nbsp;Sair</a>
                  </li>
                  <?php endif; ?>
                  
                </ul> 

                <!-- Top Bar Right Nav Elements -->
                <ul class="right menu-links">

                  <li><a href="#" data-reveal-id="modal-quem-somos">Quem Somos</a></li>

                  <!-- Divider -->
                  <li class="divider"></li>

                  <li class="has-dropdown"><a href="#">Serviços</a>
                    <ul class="dropdown">
                      <li><a href="#" data-reveal-id="modal-servicos-apoio-tecn">Apoio Técnico</a></li>
                      <li><a href="#" data-reveal-id="modal-servicos-apoio-com">Apoio Comercial</a></li>
                      <li><a href="#" data-reveal-id="modal-servicos-apoio-jur">Apoio Jurídico</a></li>
                      <li><a href="#" data-reveal-id="modal-servicos-apoio-sin">Apoio Sinistros</a></li>
                    </ul>
                  </li>

                  <li class="divider"></li>

                  <li class="has-dropdown"><a href="#">Produtos</a>
                    <ul class="dropdown">

                      <li><a href="#"  data-reveal-id="modal-produtos-riscos-financeiros">Riscos Financeiros</a>
                      </li>

                      <li><a href="#" data-reveal-id="modal-produtos-riscos-patrimoniais-resp">Riscos Patrimoniais & Responsabilidades</a>
                      </li>
                      
                      <li><a href="#" data-reveal-id="modal-produtos-riscos-diversos">Riscos Diversos</a>
                      </li>

                      <li><a href="#" data-reveal-id="modal-produtos-transportes">Transportes</a>
                      </li>

                    </ul>
                  </li>

                  <li class="divider"></li>

                  <li class="has-dropdown"><a href="#">Para Corretores</a>
                    <ul class="dropdown">
                      <li><a href="#" data-reveal-id="circularesModal">Circulares</a></li>
                      <li><a href="#" data-reveal-id="treinamentosModal">Treinamento</a></li>
                      <li><a href="#" data-reveal-id="cadastreseModal">Cadastre-se Conosco</a></li>
                      <li><a href="#" data-reveal-id="sugestoesModal">Sugestões e Reclamações</a></li>
                    </ul>
                  </li>
                  
                  <li class="has-dropdown"><a href="#">Atendimento</a>
                    <ul class="dropdown">
                      <li><a href="#" data-reveal-id="nossoCorretores">Quem é Quem</a></li>
                    </ul>
                  </li>
                  
                </ul>
              </section>
            </nav>
        </header>
        <!-- <div id="linha_header_top" class="linha_split_decor fixed"></div>
        <div id="linha_header_bottom" class="linha_split_decor fixed"></div> -->

        <?php if ($isAdmin and $this->UserIdentity('CmsUser')): ?>

        <aside id="admin-menu" class="fixed">

          <h3 id="menu_title" class="texto_centralizado">.: MENU :.</h3>

          <nav class="menu-accordion">
            <ul>
              <li style="display: none">
                <h3><span class="icon-dashboard"></span>ACL - Permissões</h3>
                <ul>
                  <li><a href="/admin/access/roles">Roles</a></li>
                  <li><a href="/admin/access/resources">Resources</a></li>
                  <li><a href="/admin/access/privileges">Privileges</a></li>
                </ul>
              </li>

              <li ng-class="{'active': isContent}">
                <h3>&nbsp;&nbsp;<span class="icon-drawer"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Conteudo</h3>
                <ul>
                  <li><a href="/admin/content/posts" target="_self"><span class="icon-compose"></span>&nbsp;&nbsp;&nbsp;&nbsp;Posts</a></li>
                  <li><a href="/admin/content/arquivostexto" target="_self"><span class="icon-note"></span>&nbsp;&nbsp;&nbsp;&nbsp;Arquivo</a></li>
                  <li><a href="/admin/content/links" target="_self"><span class="icon-link"></span>&nbsp;&nbsp;&nbsp;&nbsp;Links</a></li>
                  <li><a href="/admin/content/corretores" target="_self"><span class="icon-vcard"></span>&nbsp;&nbsp;&nbsp;&nbsp;Corretor</a></li>
                </ul>
              </li>

              <li ng-class="{'active': isUser}">
                <h3>&nbsp;&nbsp;<span class="icon-users2"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Usuários</h3>
                <ul>
                  <li><a href="/admin/access/users/index" target="_self"><span class="icon-users3"></span>&nbsp;&nbsp;&nbsp;&nbsp;Listar</a></li>
                  <li><a href="/admin/access/users/new" target="_self"><span class="icon-user-add"></span>&nbsp;&nbsp;&nbsp;&nbsp;Novo</a></li>
                </ul>
              </li>

              <li>
                <h3>&nbsp;&nbsp;<span class="icon-earth"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Site</h3>
                <ul>
                  <li>
                    <a href="/" target="_self"><span class="icon-globe"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ir Para o Site</a>
                  </li>
                  <li>
                    <a href="/auth/logout" target="_self"><span class="icon-exit"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sair</a>
                  </li>
                </ul>
              </li>

              <li style="display: none">
                <h3><span class="/admin/access/users"></span>Newsletter</h3>
                <ul>
                  <li><a href="/admin/access/users/index" target="_self">Cadastrados</a></li>
                </ul>
              </li>

            </ul>
          </nav>
        </aside>
      
        <?php endif; ?>

        <div id="main-content" ng-class="{'admin-content': isAdmin}" data-ng-cloak>

          <?php echo $this->content; ?>

        </div>

        <?php if (!$isAdmin): ?>
        <footer id="rodape" ng-class="{'admin-content': isAdmin}" class="ng-cloak">
          

          <div class="row">
          <div class="margem_top_10"></div>

            <div class="large-3 columns">
              <h3 class="titulo_footer">Mapa do Site</h3>
              <hr class="my_fancy_hr hr_gradiente_light_grey">
              <div class="margem_top_10"></div>
              
              <ul id="sitemap" class="accordion_list">
                <li>
                  <a href="">Home</a>
                </li>
                <li>
                  <a href="">Quem Somos</a>
                  <ul>
                    <li><a href="">Saiba Mais Sobre a Berkley</a></li>
                    <li><a href="">Conheça Nossos Corretores</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Serviços</a>
                  <ul>
                    <li><a href="">Apoio Técnico</a></li>
                    <li><a href="">Apoio Comercial</a></li>
                    <li><a href="">Apoio Jurídico</a></li>
                    <li><a href="">Apoio Sinistros</a></li>
                    <li><a href="">Apoio Resseguros</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Produtos</a>
                  <ul>
                    <li>
                      <a href="">Riscos Financeiros</a>
                      <ul>
                        <li><a href="">Seguro Garantia</a></li>
                        <li><a href="">Fiança Locatícia</a></li>
                      </ul>
                    </li>
                    <li>
                      <a href="">Riscos Patrimoniais & Responsabilidade Civil</a>
                      <ul>
                        <li><a href="">Riscos de Engenharia</a></li>
                        <li>
                          <a href="">Responsabilidade Civil</a>
                          <ul>
                            <li><a href="">Responsabilidade Civil Geral</a></li>
                            <li><a href="">Responsabilidade Civil Eventos</a></li>
                            <li><a href="">RC Profissional</a></li>
                            <li><a href="">D & O</a></li>
                            <li><a href="">E & O</a></li>
                          </ul>
                        </li>
                        <li>
                          <a href="">Riscos Diversos</a>
                          <ul>
                            <li><a href="">Equipamentos</a></li>
                            <li><a href="">Benfeitorias</a></li>
                          </ul>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="">Transportes</a>
                      <ul>
                        <li><a href="">Transporte Nacional</a></li>
                        <li><a href="">Transporte Internacional</a></li>
                        <li><a href="">Responsabilidade Civil do Transportador Rodoviário de Carga</a></li>
                        <li><a href="">Responsabilidade Civil por Desvio de Carga</a></li>
                        <li><a href="">Responsabilidade Civil do Transportador Aéreo Carga</a></li>
                        <li><a href="">Responsabilidade Civil do Transportador de Viagem Internacional Carga</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="">Ajuda</a>
                  <ul>
                    <li><a href="">Faq</a></li>
                    <li><a href="">Glossário</a></li>
                    <li>
                      <a href="">Informativos / Indicadores</a>
                      <ul>
                        <li><a href="">Links Úteis</a></li>
                        <li><a href="">Previsão do Tempo</a></li>
                        <li><a href="">Indicadores Econômicos</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="">Para Corretores</a>
                  <ul>
                    <li><a href="">Formulários</a></li>
                    <li><a href="">Notificações</a></li>
                    <li><a href="">Circulares</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Redes Sociais</a>
                  <ul>
                    <li><a href="https://www.facebook.com/futurauniao.consultoria?fref=ts" target="_blank">Facebook</a></li>
                    <li><a href="">Twitter</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Atendimento</a>
                  <ul>
                    <li><a href="">Fale Conosco</a></li>
                    <li><a href="">Chat On-Line</a></li>
                    <li><a href="">Telefones</a></li>
                  </ul>
                </li>
                <li>
                  <a href="">Portal do Corretor</a>
                </li>
                
              </ul>
              
            </div>

            <div class="large-4 columns logos_empresas">

              <h3 class="titulo_footer">Sobre Nós</h3>
              <hr class="my_fancy_hr hr_gradiente_light_grey">
              <div class="row">
                <div class="margem_top_10"></div>              
                <div class="small-6 columns border_right_1"><img src="/img/logo-futura-rodape.png" class="right" alt="Logo da Futura União"></div>

                <div class="small-6 columns">
                  <img src="/img/sulamerica-rodape.png" class="left" alt="Logo da SulAmerica">

                  <hr>


                  <div class="row">

                    <div class="small-6 columns btn_social_footer border_right_1">
                      <a href="" class="twitter_icon right"><span class="icon-twitter2"></span></a>
                    </div>

                    <div class="small-6 columns btn_social_footer">
                      <a href="https://www.facebook.com/futurauniao.consultoria?fref=ts" target="_blank" class="facebook_icon left"><span class="icon-facebook2"></span></a>
                    </div>

                </div>
      
                </div>
              </div>

              <br>             

              <h3>Previsão do Tempo</h3>

              <hr class="my_fancy_hr hr_gradiente_light_grey" style="margin-bottom: 15px"> 
              

              <div class="margem_top_10"><!-- Widget Previs&atilde;o de Tempo CPTEC/INPE --><iframe allowtransparency="true" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" src="http://www.cptec.inpe.br/widget/widget.php?p=244&w=n&c=909090&f=ffffff" height="46px" width="312px"></iframe><noscript>Previs&atilde;o de <a href="http://www.cptec.inpe.br/cidades/tempo/244">São Paulo/SP</a> oferecido por <a href="http://www.cptec.inpe.br">CPTEC/INPE</a></noscript><!-- Widget Previs&atilde;o de Tempo CPTEC/INPE --></div>

            </div>

            <div class="large-5 columns padding_40_left">

              <h3 class="titulo_footer">Contatos</h3>
              <hr class="my_fancy_hr hr_gradiente_light_grey" style="margin-bottom: 15px">
              <div class="font_rodape margem_top_10">
                <p>
                  <strong>Fones: </strong>(11) 3661-4491 <br>
                  <strong>E-mail: </strong>atendimento@futurauniao.com.br
                </p>
              </div>
              

              <h3 class="titulo_footer">Cotação Dolar</h3>
              <hr class="my_fancy_hr hr_gradiente_light_grey">

              <div id="img-cotacao-dolar">
                <a href="http://www.debit.com.br" target="_blank" alt="Correção monetária e cálculos trabalhistas"><img src="http://www.debit.com.br/indicadores.php" class="left" title="Correção monetária e cálculos trabalhistas"></a>
              </div>


            
            </div>

          </div>

          <br>

          <div class="barra_copyright texto_centralizado">
  
            Visite-nos: Alameda Ribeiro da Silva, 700 - 5º andar - São Paulo - SP - Cep: 01217-010<br>
            Desenvolvido por <a href="" class="link_mediaforce" rel="no-follow">Media Force - Agência Digital</a>

          </div>


        </footer>  <!-- fim rodape  -->
        <?php endif; ?>
        

      <!-- Janelas Modais INÍCIO -->
        
        <!-- Janela Modal Quem Somos -->
        <div id="modal-quem-somos" class="reveal-modal" data-reveal>
          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Quem Somos</h2>
          </div>

          <article>
            <blockquote class="bq_empresa">" As coisas mudam, as pessoas não... "
            </blockquote>
            
            <p class="subtitulo_empresa">Amigo corretor(a).
</p>
            
            <div class="texto_empresa">
              <p>Durante 18 anos, tive o privilégio de fazer parte da equipe de colaboradores da
SulAmérica Seguros.</p>
              <p>Neste período que é praticamente metade da minha vida, foi repleto de
aprendizados e realizações e posso dizer que de certa forma, ajudei a
assegurar o patrimônio e o bem estar de milhares de empresas e pessoas.</p>
              <p>É com orgulho que vejo minha participação no desenvolvimento e crescimento
desta empresa, que sempre me mostrou que trabalhando com seriedade,
determinação e honestidade o sucesso é certo.</p>
              <p>Outro grande aprendizado que tive, é que não podemos nunca parar de crescer
e de aceitarmos desafios, e baseado neste ensinamento, que no ano de 2009
nasceu a <strong>“Futura União – Assessoria e Consultoria Exclusiva da
SulAmérica”</strong>, uma empresa voltada ao atendimento <strong>EXCLUSIVO</strong> à corretores
de seguros com foco no varejo, aonde poderei utilizar todo o conhecimento que
adquiri do mercado segurador e também poder auxiliar e facilitar a
comercialização dos produtos da <strong>SULAMÉRICA</strong>.
</p>
              <p>Estamos sempre atentos as necessidades e oportunidades do mercado e
também na constante busca de atender cada vez melhor e de forma completa
nossos parceiros e clientes.</p>
              <p>Aproveito a oportunidade para convidá-lo a visitar nossas instalações e
firmarmos a nossa <strong>FUTURA UNIÃO</strong>.</p>

            </div>
          </article>

          <a class="close-reveal-modal">&#215;</a>
        </div>

        <!-- Janelas Modais de Serviços -->
        <div id="modal-servicos-apoio-tecn" class="reveal-modal paragrafo-modal" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Apoio Técnico</h2>
          </div>

          <p>Para a realização de um atendimento rápido e eficaz, contamos com uma estrutura operacional diferenciada no mercado de seguros, com profissionais experientes e com conhecimentos sobre os mais variados produtos e serviços exclusivamente da SulAmérica, que nos permite ter mais agilidade nas respostas.</p>
          <a class="close-reveal-modal">&#215;</a>
        </div>

        <div id="modal-servicos-apoio-com" class="reveal-modal paragrafo-modal" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Apoio Comercial</h2>
          </div>

          <p>Nossa área comercial conta com profissionais com vasta experiência no mercado de seguros, prestando o apoio e suporte para que você Corretor de Seguros possa desenvolver um bom trabalho com a SulAmérica, alavancando suas vendas.</p>
          <a class="close-reveal-modal">&#215;</a>
        </div>

        <div id="modal-servicos-apoio-jur" class="reveal-modal paragrafo-modal" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Apoio Jurídico</h2>
          </div>
          <p>A Futura União, visando o atendimento diferenciado aos seus corretores, oferece apoio nas diversas áreas jurídicas, como: Seguros, Trabalhista, Contratos, Responsabilidade Civil, Consumidor, Imobiliário e afins.</p>
          <p>Assim, no intuito de apoiá-los, informamos que consultas simples e esclarecimentos iniciais, serão realizados sem cobrança de valores. Caso haja necessidade da prestação de serviços jurídicos e/ou análise mais complexa, apresentaremos uma proposta com valores diferenciados para os corretores vinculados à Futura União.</p>
          <a class="close-reveal-modal">&#215;</a>
        </div>

        <div id="modal-servicos-apoio-sin" class="reveal-modal paragrafo-modal" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Apoio Sinistros</h2>
          </div>

          <p>Com nossos profissionais exclusivos da SulAmérica, conseguimos agilizar os procedimentos em caso de Sinistros com mais segurança e rapidez.</p>
          <a class="close-reveal-modal">&#215;</a>
        </div>

        <div id="modal-servicos-apoio-resseg" class="reveal-modal paragrafo-modal" data-reveal>
          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Apoio Resseguros</h2>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam in debitis maiores ad, corrupti facere est doloribus inventore odit quasi, nihil atque beatae veniam velit sit ratione dignissimos! Aliquam quisquam deserunt voluptatibus eum, praesentium commodi debitis doloribus dolores vero esse voluptates molestias. Corporis adipisci voluptatum nam, suscipit ab molestiae aperiam harum, incidunt odio doloribus, aut? Non deleniti qui et aspernatur corrupti nesciunt, quisquam sunt, distinctio pariatur, at tempore quo. Illum culpa ut facilis eos impedit, quibusdam, enim officiis repellendus placeat reprehenderit ab. Veritatis, dolore, nihil. At aliquid, neque sequi iusto, eligendi quisquam maxime, provident rem facilis eos illo est repellat.</p>
          <a class="close-reveal-modal">&#215;</a>
        </div>
        <!-- fim Janelas Modais de Serviços -->


        <!-- Janelas Modais de Produtos  -->

        <div id="modal-produtos-riscos-financeiros" class="reveal-modal produtos-pagina" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Riscos Financeiros</h2>
          </div>

          <div>
            <dl class="accordion" data-accordion="riscosFinGropo">
              <dd class="accordion-navigation">

                <a href="#riscosfin-seguro-garantia">Seguro Garantia</a>
                <div id="riscosfin-seguro-garantia" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscosfin-seguro-garantia-fin">Finalidade</a></dd>
                    <dd><a href="#riscosfin-seguro-garantia-cob">Coberturas</a></dd>
                    <dd><a href="#riscosfin-seguro-garantia-con">Como Contratar</a></dd>
                    <dd><a href="#riscosfin-seguro-garantia-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscosfin-seguro-garantia-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscosfin-seguro-garantia-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscosfin-seguro-garantia-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscosfin-seguro-garantia-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">
                <a href="#riscosfin-fianca-locataria">Fiança Locatícia</a>
                <div id="riscosfin-fianca-locataria" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscosfin-fianca-locataria-fin">Finalidade</a></dd>
                    <dd><a href="#riscosfin-fianca-locataria-cob">Coberturas</a></dd>
                    <dd><a href="#riscosfin-fianca-locataria-con">Como Contratar</a></dd>
                    <dd><a href="#riscosfin-fianca-locataria-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscosfin-fianca-locataria-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscosfin-fianca-locataria-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscosfin-fianca-locataria-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscosfin-fianca-locataria-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

            </dl>
          </div>
          
          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal-produtos-riscos-financeiros  -->

        <div id="modal-produtos-riscos-patrimoniais-resp" class="reveal-modal produtos-pagina" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Riscos Patrimoniais & Responsabilidades</h2>
          </div>

          <div>
            <dl class="accordion" data-accordion="riscosPRGrupo">
              <dd class="accordion-navigation">

                <a href="#riscospr-responsabilidade-de-engenharia">Responsabilidade de Engenharia</a>
                <div id="riscospr-responsabilidade-de-engenharia" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscospr-responsabilidade-de-engenharia-fin">Finalidade</a></dd>
                    <dd><a href="#riscospr-responsabilidade-de-engenharia-cob">Coberturas</a></dd>
                    <dd><a href="#riscospr-responsabilidade-de-engenharia-con">Como Contratar</a></dd>
                    <dd><a href="#riscospr-responsabilidade-de-engenharia-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscospr-responsabilidade-de-engenharia-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-de-engenharia-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-de-engenharia-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscp-rc-prof-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">

                <a href="#riscospr-responsabilidade-geral">Responsabilidade Civil Geral</a>
                <div id="riscospr-responsabilidade-geral" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscospr-responsabilidade-geral-fin">Finalidade</a></dd>
                    <dd><a href="#riscospr-responsabilidade-geral-cob">Coberturas</a></dd>
                    <dd><a href="#riscospr-responsabilidade-geral-con">Como Contratar</a></dd>
                    <dd><a href="#riscospr-responsabilidade-geral-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscospr-responsabilidade-geral-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-geral-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-geral-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-geral-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">

                <a href="#riscospr-responsabilidade-eventos">Responsabilidade Civil Eventos</a>
                <div id="riscospr-responsabilidade-eventos" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscospr-responsabilidade-eventos-fin">Finalidade</a></dd>
                    <dd><a href="#riscospr-responsabilidade-eventos-cob">Coberturas</a></dd>
                    <dd><a href="#riscospr-responsabilidade-eventos-con">Como Contratar</a></dd>
                    <dd><a href="#riscospr-responsabilidade-eventos-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscospr-responsabilidade-eventos-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-eventos-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-eventos-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-responsabilidade-eventos-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">

                <a href="#riscospr-profissional">RC Profissional</a>
                <div id="riscospr-profissional" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscospr-profissional-fin">Finalidade</a></dd>
                    <dd><a href="#riscospr-profissional-cob">Coberturas</a></dd>
                    <dd><a href="#riscospr-profissional-con">Como Contratar</a></dd>
                    <dd><a href="#riscospr-profissional-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscospr-profissional-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-profissional-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-profissional-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-profissional-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">

                <a href="#riscospr-do">D & O</a>
                <div id="riscospr-do" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscospr-do-fin">Finalidade</a></dd>
                    <dd><a href="#riscospr-do-cob">Coberturas</a></dd>
                    <dd><a href="#riscospr-do-con">Como Contratar</a></dd>
                    <dd><a href="#riscospr-do-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscospr-do-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-do-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-do-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-do-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">

                <a href="#riscospr-eo">E & O</a>
                <div id="riscospr-eo" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#riscospr-eo-fin">Finalidade</a></dd>
                    <dd><a href="#riscospr-eo-cob">Coberturas</a></dd>
                    <dd><a href="#riscospr-eo-con">Como Contratar</a></dd>
                    <dd><a href="#riscospr-eo-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="riscospr-eo-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-eo-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-eo-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="riscospr-eo-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>
              
            </dl>

          </div>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal-produtos-riscos-patrimoniais-resp  -->

        <div id="modal-produtos-riscos-diversos" class="reveal-modal produtos-pagina" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Riscos Diversos</h2>
          </div>

          <div>

            <dl class="accordion" data-accordion="riscosDiver">

              <dd class="accordion-navigation">

                <a href="#prod-pn-riscd-equip">Equipamentos</a>

                <div id="prod-pn-riscd-equip" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#prod-pn-riscd-equip-fin">Finalidade</a></dd>
                    <dd><a href="#prod-pn-riscd-equip-cob">Coberturas</a></dd>
                    <dd><a href="#prod-pn-riscd-equip-con">Como Contratar</a></dd>
                    <dd><a href="#prod-pn-riscd-equip-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="prod-pn-riscd-equip-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-equip-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-equip-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-equip-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>

              </dd>

              <dd class="accordion-navigation">

                <a href="#prod-pn-riscd-ben">Benfeitorias</a>

                <div id="prod-pn-riscd-ben" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#prod-pn-riscd-ben-fin">Finalidade</a></dd>
                    <dd><a href="#prod-pn-riscd-ben-cob">Coberturas</a></dd>
                    <dd><a href="#prod-pn-riscd-ben-con">Como Contratar</a></dd>
                    <dd><a href="#prod-pn-riscd-ben-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="prod-pn-riscd-ben-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-ben-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-ben-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-ben-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>

              </dd>

            </dl>

          </div>
          
          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal-produtos-riscos-financeiros  -->

        <div id="modal-produtos-transportes" class="reveal-modal produtos-pagina" data-reveal>
          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Transportes</h2>
          </div>
          
          <div>
            
            <dl class="accordion" data-accordion="transpGrupo">

              <dd class="accordion-navigation">
                <a href="#transp-transporte-nacional">Transporte Nacional</a>
                <div id="transp-transporte-nacional" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#prod-pn-riscd-ben-fin">Finalidade</a></dd>
                    <dd><a href="#prod-pn-riscd-ben-cob">Coberturas</a></dd>
                    <dd><a href="#prod-pn-riscd-ben-con">Como Contratar</a></dd>
                    <dd><a href="#prod-pn-riscd-ben-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="prod-pn-riscd-ben-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-ben-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-ben-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="prod-pn-riscd-ben-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">
                <a href="#transp-transporte-internacional">Transporte Internacional</a>
                <div id="transp-transporte-internacional" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#transp-transporte-internacional-fin">Finalidade</a></dd>
                    <dd><a href="#transp-transporte-internacional-cob">Coberturas</a></dd>
                    <dd><a href="#transp-transporte-internacional-con">Como Contratar</a></dd>
                    <dd><a href="#transp-transporte-internacional-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="transp-transporte-internacional-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-transporte-internacional-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-transporte-internacional-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-transporte-internacional-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">
                <a href="#transp-tranportador-rodoviario">Responsabilidade Civil do Transportador Rodoviário de Carga</a>
                <div id="transp-tranportador-rodoviario" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#transp-tranportador-rodoviario-fin">Finalidade</a></dd>
                    <dd><a href="#transp-tranportador-rodoviario-cob">Coberturas</a></dd>
                    <dd><a href="#transp-tranportador-rodoviario-con">Como Contratar</a></dd>
                    <dd><a href="#transp-tranportador-rodoviario-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="transp-tranportador-rodoviario-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-tranportador-rodoviario-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-tranportador-rodoviario-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-tranportador-rodoviario-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">
                <a href="#transp-desvio-de-carga">Responsabilidade Civil por Desvio de Carga</a>
                <div id="transp-desvio-de-carga" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#transp-desvio-de-carga-fin">Finalidade</a></dd>
                    <dd><a href="#transp-desvio-de-carga-cob">Coberturas</a></dd>
                    <dd><a href="#transp-desvio-de-carga-con">Como Contratar</a></dd>
                    <dd><a href="#transp-desvio-de-carga-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="transp-desvio-de-carga-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-desvio-de-carga-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-desvio-de-carga-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-desvio-de-carga-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">
                <a href="#transp-transportador-aereo">Responsabilidade Civil do Transportador Aéreo Carga</a>
                <div id="transp-transportador-aereo" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#transp-transportador-aereo-fin">Finalidade</a></dd>
                    <dd><a href="#transp-transportador-aereo-cob">Coberturas</a></dd>
                    <dd><a href="#transp-transportador-aereo-con">Como Contratar</a></dd>
                    <dd><a href="#transp-transportador-aereo-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="transp-transportador-aereo-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-transportador-aereo-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-transportador-aereo-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-transportador-aereo-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

              <dd class="accordion-navigation">
                <a href="#transp-viagem-internacional">Responsabilidade Civil do Transportador de Viagem Internacional</a>
                <div id="transp-viagem-internacional" class="content">
                  <dl class="tabs tabs_accordion" data-tab>
                    <dd class="active"><a href="#transp-viagem-internacional-fin">Finalidade</a></dd>
                    <dd><a href="#transp-viagem-internacional-cob">Coberturas</a></dd>
                    <dd><a href="#transp-viagem-internacional-con">Como Contratar</a></dd>
                    <dd><a href="#transp-viagem-internacional-van">Vantagens</a></dd>
                  </dl>
                  <div class="tabs-content">
                    <div class="content active" id="transp-viagem-internacional-fin">
                      <p>Finalidade  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-viagem-internacional-cob">
                      <p>Coberturas  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-viagem-internacional-con">
                      <p>Como Contratar  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                    <div class="content" id="transp-viagem-internacional-van">
                      <p>Vantagens  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel ullam iure iusto quia, aliquid impedit est ipsa adipisci esse omnis molestiae, dolorem, itaque nesciunt perferendis architecto consequuntur earum. Harum, nesciunt!</p>
                    </div>
                  </div>
                </div>
              </dd>

            </dl>

          </div>

          <a class="close-reveal-modal">&#215;</a>

        </div> <!-- fim modal-produtos-transportes  -->

        <div ng-controller="FormulariosCtrl" id="formulariosModal" class="reveal-modal conteudo-lista-estilo" data-reveal>

          <div class="row margem_bottom_10" >
            <div class="fundo_titulo_modal">
              <h2 class="titulo_modal">Formulários</h2>
            </div>
          </div>

          <div class="lista-conteudo">
            <div ng-show="loadingFormularios" class="carregando_informacao texto_centralizado">
              <img src="/img/carregando.gif" alt="">
            </div>
            <div ng-hide="loadingFormularios">
              <strong>
                <ng-pluralize count="formularios.length"
                                   when="{'0': 'Sem Formulários Cadastrados!',
                                   'one': '1 Formulário:',
                                     'other': '{} Formulários:'}">
                </ng-pluralize>
              </strong>
            </div>
            
            <ul class="ng-cloak">
              
              <li dir-paginate="formulario in formularios | filter:q | itemsPerPage: pageSize: 'forms'" current-page="currentPage" pagination-id="forms">
                {{ formulario.titulo }} | <a href="/{{ formulario.endereco }}" target="_self" download>download</a>
              </li>
            
            </ul>
            
            <dir-pagination-controls pagination-id="forms" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
          </div>
              
          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal formularios -->

        <div ng-controller="NotificacoesCtrl" id="notificacoesModal" class="reveal-modal conteudo-lista-estilo" data-reveal>

          <div class="row margem_bottom_10" >
            <div class="fundo_titulo_modal">
              <h2  class="titulo_modal">Notificações</h2>
            </div>

          </div>

          <div class="lista-conteudo">
            <dl class="tabs" data-tab>
              <dd class="active"><a href="#panel_paginas_notificacoes">Paginas</a></dd>
              <dd><a href="#panel_arquivos_notificacoes">Arquivos</a></dd>
            </dl>
            
            
            
            <div class="tabs-content">
              <div class="content active" id="panel_paginas_notificacoes">
                <div ng-show="loadingNotificacoes" class="carregando_informacao texto_centralizado">
                <img src="/img/carregando.gif" alt="">
              </div>
              <div ng-hide="loadingNotificacoes">
                <strong>
                  <ng-pluralize count="notificacoes.length"
                             when="{'0': 'Sem Notificações Cadastradas!',
                             'one': '1 Notificação:',
                               'other': '{} Notificações:' }">
                  </ng-pluralize>
                </strong>
              </div>
                <ul class="ng-cloak">
                  
                <li dir-paginate="notificacao in notificacoes | filter:q | itemsPerPage: pageSize: 'notis'" current-page="currentPage" pagination-id="notis">
                  <a href="/conteudo/notificações/{{ notificacao.id }}" target="_self">
                    {{ notificacao.titulo }}
                  </a>
                  &nbsp;|&nbsp;
                  Em {{ notificacao.criado_em.date }} 
                  &nbsp;Por Nome do Criador
            
                </li>
            
              </ul>
            
              <dir-pagination-controls pagination-id="notis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
              </div>
            
              <div class="content" id="panel_arquivos_notificacoes">
                <div ng-show="loadingNotificacoesArquivos" class="carregando_informacao texto_centralizado">
                <img src="/img/carregando.gif" alt="">
              </div>
              <div ng-hide="loadingNotificacoesArquivos">
                <strong>
                  <ng-pluralize count="notificacoesArquivos.length"
                             when="{'0': 'Sem Arquivos de Notificação Cadastradas!',
                             'one': '1 Arquivo de Notificação:',
                               'other': '{} Arquivos de Notificações:'}">
                  </ng-pluralize>
                </strong>
              </div>
                <ul class="ng-cloak">
                  
                <li dir-paginate="notificacaoArquivo in notificacoesArquivos | filter:w | itemsPerPage: pageSizeArquivos: 'notisarquis'" current-page="currentPageArquivos"  pagination-id="notisarquis">
                  {{ notificacaoArquivo.titulo }} | <a href="/{{ notificacaoArquivo.endereco }}" target="_self" download>download</a>
            
                </li>
            
              </ul>
            
              <dir-pagination-controls pagination-id="notisarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
              </div>
            </div>
          </div>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal notificacoes -->

        <div ng-controller="CircularesCtrl" id="circularesModal" class="reveal-modal conteudo-lista-estilo" data-reveal>

          <div class="row margem_bottom_10" >
            <div class="fundo_titulo_modal_2">
              <div class="circle">
                
              </div>
              <div class="linha_vertical">
                
              </div>
              <div class="linha_horizontal">
                
              </div>
              <h2 class="titulo_modal">Circulares</h2>
            </div>
          </div>

          <div class="lista-conteudo">
            <dl class="tabs" data-tab>
              <dd class="active"><a href="#panel_paginas_circulares">Paginas</a></dd>
              <dd><a href="#panel_arquivos_circulares">Arquivos</a></dd>
            </dl>
            
            <div class="tabs-content">
              <div class="content active" id="panel_paginas_circulares">
                <div ng-show="loadingCirculares" class="carregando_informacao texto_centralizado">
                <img src="/img/carregando.gif" alt="">
              </div>
              <div ng-hide="loadingCirculares">
                <strong>
                  <ng-pluralize count="circulares.length"
                             when="{'0': 'Sem Circulares Cadastradas!',
                             'one': '1 Circular:',
                               'other': '{} Circulares:'}">
                  </ng-pluralize>
                </strong>
              </div>
                <ul class="ng-cloak">
                <li dir-paginate="circular in circulares | filter:q | itemsPerPage: pageSize: 'circus'" current-page="currentPage"  pagination-id="circus">
                  <a href="/conteudo/circulares/{{ circular.id }}" target="_self">
                    {{ circular.titulo }}
                  </a>
                  &nbsp;|&nbsp;
                  Em {{ circular.criado_em.date }}  
                  &nbsp;Por Nome do Criador
            
                </li>
            
              </ul>
            
              <dir-pagination-controls pagination-id="circus" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
              </div>
            
              <div class="content" id="panel_arquivos_circulares">
                <div ng-show="loadingCircularesArquivos" class="carregando_informacao texto_centralizado">
                <img src="/img/carregando.gif" alt="">
              </div>
              <div ng-hide="loadingCircularesArquivos">
                <strong>
                  <ng-pluralize count="circularesArquivos.length"
                             when="{'0': 'Sem Arquivos de Circular Cadastradas!',
                             'one': '1 Arquivo de Circular:',
                               'other': '{} Arquivos de Circulares:'}">
                </ng-pluralize>
                </strong>
              </div>
                <ul class="ng-cloak">
                <li dir-paginate="circularArquivo in circularesArquivos | filter:q | itemsPerPage: pageSizeArquivos: 'circusarquis'" current-page="currentPageArquivos" pagination-id="circusarquis">
                  <a href="" target="_self">
                    {{ circularArquivo.titulo }}
                  </a>
                  &nbsp;|&nbsp;
                  Em {{ circularArquivo.criado_em.date }} 
                  &nbsp;Por Nome do Criador
            
                </li>
            
              </ul>
            
              <dir-pagination-controls pagination-id="circusarquis" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
              </div>
            </div>
          </div>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal circulares -->

        <div id="faqModal" ng-controller="FaqCtrl" class="reveal-modal conteudo-lista-estilo" data-reveal>

          <div class="row margem_bottom_10 padding_left_10" >
            <div class="fundo_titulo_modal_2">
              <div class="circle">
                
              </div>
              <div class="linha_vertical">
                
              </div>
              <div class="linha_horizontal">
                
              </div>
              <h2 class="titulo_modal">FAQ - {{ currentPage }}</h2>
            </div>
          
          </div>

          <div class="row">

            <div class="large-3 small-12 columns">
              <label for="right-label" class="right inline"><strong>Procurar Pergunta: </strong></label>
            </div>

            <div class="large-9 small-12 columns">
              <input ng-model="q" id="search" class="form-control expand input_search" placeholder="Escreva a pergunta">
            </div>

          </div>

              <div ng-show="loadingFaqs" class="carregando_informacao texto_centralizado">
                <img src="/img/carregando.gif" alt="">
              </div>
                    
                    <dl id="faq-accordion" class="accordion" data-accordion="myAccordionGroup">
                  <dd class="accordion-navigation" dir-paginate="faq in faqs | filter:q | itemsPerPage: pageSize: 'faq'" current-page="currentPage" pagination-id="faq">
                    <a href="#faq-{{ faq.id }}">{{faq.titulo}}</a>
                    <div id="faq-{{ faq.id }}" class="content">
                      <p ng-bind-html="renderHtml(faq.conteudo)"></p>
                    </div>
                  </dd>
                </dl>

                <dir-pagination-controls pagination-id="faq" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html"></dir-pagination-controls>


              
          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal faq -->

        <div ng-controller="GlossarioCtrl" id="glossarioModal" class="reveal-modal conteudo-lista-estilo" data-reveal>

          <div class="row margem_bottom_10 padding_left_10" >
            <div class="fundo_titulo_modal_2">
              <div class="circle">
                
              </div>
              <div class="linha_vertical">
                
              </div>
              <div class="linha_horizontal">
                
              </div>
              <h2 class="titulo_modal">Glossário</h2>
            </div>
          
          </div>

          <div class="row">

            <div class="large-3 small-12 columns">
              <label for="right-label" class="right inline"><strong>Procurar Termo: </strong></label>
            </div>

            <div class="large-9 small-12 columns">
              <input ng-model="q" id="search" class="form-control expand input_search" placeholder="Escreva o termo">
            </div>

          </div>

          <div ng-show="loadinGlossario" class="carregando_informacao texto_centralizado">
            <img src="/img/carregando.gif" alt="">
          </div>

          <ul class="ng-cloak">
            <li dir-paginate="termo in glossario | filter:q | itemsPerPage: pageSize: 'gloss'" current-page="currentPage" pagination-id="gloss">
              
              <strong>{{ termo.titulo }}</strong>: <span ng-bind-html="renderHtml(termo.conteudo)"></span>

            </li>

          </ul>

          <dir-pagination-controls pagination-id="gloss" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>

          <a class="close-reveal-modal ">&#215;</a>
        </div> <!-- fim modal glossario -->

        <div ng-controller="LinksCtrl" id="linksModal" class="reveal-modal tiny" data-reveal>

          <div ng-controller="LinksCtrl" id="widget_links_uteis">
            <div>
              <div class="fundo_titulo_modal_2">
                <div class="circle">
                  
                </div>
                <div class="linha_vertical">
                  
                </div>
                <div class="linha_horizontal">
                  
                </div>
                <h2 class="titulo_modal">Links Uteis <span class="ng-cloak">{{tableParams.page()}}</span></h2>
              </div>
            </div>

            <div class="column-content widget-top widget-box padding_vinte">

              <div ng-show="loadingLinks" class="carregando_informacao texto_centralizado">
                <img src="/img/carregando.gif" alt="">
              </div>

              <table ng-table="tableParams" class="table_clean ng-cloak">
                      <thead>

                      </thead>
                      <tbody>
                          <tr ng-repeat="link in $data">
                              <td data-title="'descricao'"><a class="links_uteis" href="{{link.href}}" target="_blank"><img src="http://g.etfv.co/{{link.href}}" alt="Google" width="16" height="16" />&nbsp;&nbsp;&nbsp;{{link.descricao}}</a></td>
                          </tr>
                      </tbody>

                      
                </table>
            </div>
          </div>

          <a class="close-reveal-modal ">&#215;</a>
        </div> <!-- fim modal glossario -->

        <div id="indicadoresModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Indicadores Econômicos e Ferramentas</h2>
          </div>

          <dl class="tabs vertical" data-tab>
            <dd class="active"><a href="#indicadoresInflacao">Indicadores de inflação</a></dd>
            <dd><a href="#indicadoresDiversos">Indicadores Diversos</a></dd>
            <dd><a href="#dolarUltimos">Dólar (Fechamento dos últimos Dias)</a></dd>
            <dd><a href="#euroUltimos">Euro (Fechamento dos últimos Dias)</a></dd>
            <dd><a href="#conversorMoedas">Conversor de moedas)</a></dd>
          </dl>
          <div class="tabs-content">
            <div class="content active" id="indicadoresInflacao">
  
              <script type="text/javascript" src="http://www.debit.com.br/resumogratuito.php?info=inflacao"></script>
            </div>
            <div class="content" id="indicadoresDiversos">
              <script type="text/javascript" src="http://www.debit.com.br/resumogratuito.php?info=diversos"></script>
            </div>
            <div class="content" id="dolarUltimos">
              <script type="text/javascript" src="http://www.debit.com.br/resumogratuito.php?info=dolar"></script>
            </div>
            <div class="content" id="euroUltimos">
              <script type="text/javascript" src="http://www.debit.com.br/resumogratuito.php?info=euro"></script>
            </div>
            <div class="content" id="conversorMoedas">
              <div style="text-align: center; width:180px; font-size: 10px; font-family: Verdana; float: left;" class="conversor_moeda"><iframe style="border:1px solid #C0C0C0; width:180px; height:300px;"  scrolling="no" marginwidth="0" marginheight="0" frameborder="0" src="http://pt.loobiz.com/BRL-vs-USD.htm"><a href="http://pt.loobiz.com/BRL-vs-USD.htm">BRL USD</a><div style="text-align: center; width:180px; font-size: 10px; font-family: Verdana;"></iframe><br/><a href="http://pt.loobiz.com/moeda-conversor/">Conversor de Moedas</a><br/><a href="http://pt.loobiz.com/moeda-conversor/real+us-dolar">BRL / USD</a></div>
              <div style="text-align: center; width:180px; font-size: 10px; font-family: Verdana; float: left;" class="conversor_moeda"><iframe style="border:1px solid #C0C0C0; width:180px; height:300px;"  scrolling="no" marginwidth="0" marginheight="0" frameborder="0" src="http://pt.loobiz.com/BRL-vs-EUR.htm"><a href="http://pt.loobiz.com/BRL-vs-EUR.htm">BRL EUR</a><div style="text-align: center; width:180px; font-size: 10px; font-family: Verdana;"></iframe><br/><a href="http://pt.loobiz.com/moeda-conversor/">Conversor de Moedas</a><br/><a href="http://pt.loobiz.com/moeda-conversor/real+euro">BRL / EUR</a></div>
            </div>
          </div>         

          <a class="close-reveal-modal ">&#215;</a>
        </div> <!-- fim modal glossario -->

        <div ng id="nossoCorretores" class="reveal-modal" data-reveal ng-controller="CorretoresCtrl">
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Nossos Colaboradores <span class="ng-cloak">{{ currentPage }}</span></h2>
          </div>

          <div class="row margem_bottom_10 padding_left_10" >
            <p class="light_gray_f subtitulo">Entre em contato com um de nossos colaboradores:</p>
          </div>

          <div ng-show="loadingCorretores" class="carregando_informacao texto_centralizado">
            <img src="/img/carregando.gif" alt="">
          </div>

          <div class="ng-cloak" pagination-id="colabor" dir-paginate="corretor in corretores | filter:q | itemsPerPage: pageSize: 'colabor'" current-page="currentPage">

            <div class="row">
              <div class="large-3 small-12 columns">
                <span ng-show="corretor.foto.length">
                  {{ corretor.foto }}
                </span>
                <span ng-hide="corretor.foto.length">
                  <img src="/img/corretores/sem-foto.png" alt="Sem Foto Corretor">
                </span>
              </div>
              <div class="large-8 large-offset-1 small-12 columns">
                <table style="width: 100%">
                  <tbody>
                    <tr>
                      <td><strong>Nome:</strong></td>
                      <td><span>{{ corretor.nome }}</span><br></td>
                    </tr>

                    <span ng-show="corretor.area.length > 0">
                      <tr>
                        <td><strong>Area:</strong></td>
                        <td><span>{{ corretor.area }}</span></td>
                      </tr>
                    </span>
                    
                    <span ng-show="corretor.cargo.length > 0">
                      <tr>
                        <td><strong>Cargo:</strong></td>
                        <td><span>{{ corretor.cargo }}</span></td>
                      </tr>
                    </span>
                    
                    <span ng-show="corretor.filial.length > 0">
                      <tr>
                        <td><strong>Filial:</strong></td>
                        <td><span>{{ corretor.filial }}</span></td>
                      </tr>
                    </span>

                    <tr>
                      <td><strong>E-mail:</strong></td>
                      <td><span>{{ corretor.email }}</span></td>
                    </tr>
                    
                    <tr>
                      <td>
                        <strong>
                          <ng-pluralize count="corretor.telefones.length"
                                           when="{'0': 'Sem telefone!',
                                               'one': '1 Telefone:',
                                               'other': '{} Telefones:'}">
                          </ng-pluralize>
                        </strong>
                      </td>
                      <td>
                        <span ng-repeat="telefone in corretor.telefones">
                          
                          <div ng-if="telefone.tipo=='celular'"><span class="icon-mobile">{{ telefone.num }}</span></div>
                          <div ng-if="telefone.tipo=='telefone'"><span class="icon-phone">{{ telefone.num }}</span></div>
                          <div ng-if="telefone.tipo=='fax'"><span class="icon-uniE603">{{ telefone.num }}</span></div>
                          
                        </span>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <dir-pagination-controls pagination-id="colabor" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal nossoCorretores -->

        <div ng-controller="FormulariosCtrl" id="formulariosModal" class="reveal-modal" data-reveal>

          <div class="row margem_bottom_10 padding_left_10" >
            <h1 class="titulo-modal titulo-parte-home-light-green ">Formulários</h1>
            <hr class="my_fancy_hr hr_gradiente_light_grey">
          </div>

          <div ng-show="loadingFormularios" class="carregando_informacao texto_centralizado">
            <img src="/img/carregando.gif" alt="">
          </div>
          <div ng-hide="loadingFormularios">
            <strong>
              <ng-pluralize count="formularios.length"
                                 when="{'0': 'Sem Formulários Cadastrados!',
                                 'one': '1 Formulário:',
                                   'other': '{} Formulários:'}">
              </ng-pluralize>
            </strong>
          </div>

          <ul class="ng-cloak">
            
            <li dir-paginate="formulario in formularios | filter:q | itemsPerPage: pageSize: 'forms'" current-page="currentPage" pagination-id="forms">
              {{ formulario.titulo }} | <a href="/{{ formulario.endereco }}" target="_self" download>download</a>
            </li>

          </ul>

          <dir-pagination-controls pagination-id="forms" boundary-links="true" on-page-change="pageChangeHandler(newPageNumber)" template-url="/templates/dirPagination.tpl.html" class="ng-cloak"></dir-pagination-controls>
              
          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal formularios -->

        <div id="servicosModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Serviços</h2>
          </div>

          <ul class="inline-list padding_left_10 padding_20_top">
            <li>
              <a href="#" data-reveal-id="modal-servicos-apoio-tecn">Apoio Técnico</a>
            </li>
            <li>
              <a href="#" data-reveal-id="modal-servicos-apoio-com">Apoio Comercial</a>
            </li>
            <li>
              <a href="#" data-reveal-id="modal-servicos-apoio-jur">Apoio Jurídico</a>
            </li>
            <li>
              <a href="#" data-reveal-id="modal-servicos-apoio-sin">Apoio Sinistros</a>
            </li>
          </ul>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal serviços -->

        <div id="produtosModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Produtos</h2>
          </div>

          <ul class="inline-list padding_left_10 padding_20_top">
            <li>
              <a href="#"  data-reveal-id="modal-produtos-riscos-financeiros">Riscos Financeiros</a>
            </li>
            <li>
              <a href="#" data-reveal-id="modal-produtos-riscos-patrimoniais-resp">Riscos Patrimoniais & Responsabilidades</a>
            </li>
            <li>
              <a href="#" data-reveal-id="modal-produtos-riscos-diversos">Riscos Diversos</a>
            </li>
            <li>
              <a href="#" data-reveal-id="modal-produtos-transportes">Transportes</a>
            </li>
          </ul>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal produtos -->
      
        <div id="paraCorretoresModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Para Corretores</h2>
          </div>
          
          <ul class="inline-list padding_left_10 padding_20_top">
            <li>
              <a href="#" data-reveal-id="formulariosModal">Formulários</a>
            </li>
            <li>
              <a href="#" data-reveal-id="notificacoesModal">Notificações</a>
            </li>
            <li>
              <a href="#" data-reveal-id="circularesModal">Circulares</a>
            </li>
          </ul>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal produtos -->

        <div ng-controller="FormContatoCtrl" id="formularioModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Fale Conosco</h2>
          </div>

          

          <div class="row padding_left_10" >
            <p class="light_gray_f subtitulo">Os campos com asterisco (*) são obrigatórios.</p>
          </div>

          <p ng-class="result" style="padding: 15px; margin: 0;">{{ resultMessage }}</p>

          <form ng-submit="submit(contactform)" name="contactform" method="post" class="form-horizontal" role="form">
                <div class="row" ng-class="{ 'error': contactform.inputNome.$invalid && submitte*d }">
                  <div class="small-12 columns">
                      <div class="row">
                        <div class="small-2 columns">
                          <label for="inputNome" class="left">* Nome: </label>
                        </div>
                        <div class="small-10 columns">
                            <input ng-model="formData.inputNome" type="text" class="form-control" id="inputNome" name="inputNome" placeholder="Seu nome" required>
                        </div>
                      </div>
                    </div>
                </div>

                <div class="row">
                  <div class="large-6 small-12 columns">
                
                      <div class="row">
                        <div class="small-3 columns">
                          <label for="inputCorretora" class="left">Corretora: </label>
                        </div>
                        <div class="small-9 columns">
                            <input ng-model="formData.inputCorretora" type="text" class="form-control" id="inputCorretora" name="inputCorretora" placeholder="Sua corretora">
                        </div>
                      </div>
                  </div>

                  <div class="large-6 small-12 columns">

                      <div class="row">
                        <div class="small-3 columns">
                          <label for="inputTelefone" class="left">Telefone: </label>
                        </div>
                        <div class="small-9 columns">
                            <input ng-model="formData.inputTelefone" type="text" class="form-control" id="inputTelefone" name="inputTelefone" placeholder="Seu telefone">
                        </div>
                      </div>
                  </div>
                </div>

                <div class="row">
                  <div class="large-6 columns" ng-class="{ 'error': contactform.inputEmail.$invalid && submitted }">

                      <div class="row">
                        <div class="small-3 columns">
                          <label for="inputEmail" class="left">* Email: </label>
                        </div>
                        <div class="small-9 columns">
                            <input ng-model="formData.inputEmail" type="email" class="form-control" id="inputEmail" name="inputEmail" placeholder="Your Email" required>
                        </div>
                      </div>
                  </div>
                  
                  <div class="large-6 columns">
          
                      <div class="row">
                        <div class="small-3 columns">
                          <label for="inputRamoProd" class="left">Ramo/Produto: </label>
                        </div>
                        <div class="small-9 columns">
                            <input ng-model="formData.inputRamoProd" type="text" class="form-control" id="inputRamoProd" name="inputRamoProd" placeholder="Seu produto/ramo">
                        </div>
                      </div>
                  </div>
                </div>

                <div class="row" ng-class="{ 'error': contactform.inputAssunto.$invalid && submitted }">
                  <div class="small-12 columns">
                      <div class="row">
                        <div class="small-2 columns">
                          <label for="inputAssunto" class="left">* Assunto:</label>
                        </div>
                        <div class="small-10 columns">
                            <input ng-model="formData.inputAssunto" type="text" class="form-control" id="inputAssunto" name="inputAssunto" placeholder="Assunto da mensagem" required>
                        </div>
                      </div>
                    </div>
                </div>

                <div class="row" ng-class="{ 'error': contactform.inputMensagem.$invalid && submitted }">

                      <div class="small-12 columns">
                        <label for="inputMensagem" class="left">* Mensagem:</label>
                      </div>
                      <div class="small-12 columns">
                          <textarea ng-model="formData.inputMensagem" class="form-control" rows="4" id="inputMensagem" name="inputMessage" placeholder="Sua mensagem..." required></textarea>
                      </div>

                </div>
                <div class="row">
                    <div class="small-12 columns">
                        <button type="submit" class="button expand" ng-disabled="submitButtonDisabled">
                            Enviar
                        </button>
                    </div>
                </div>
            </form>
            

          <a class="close-reveal-modal ">&#215;</a>
        </div> <!-- fim modal formulario contato -->

        <div id="treinamentosModal" class="reveal-modal" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Treinamento</h2>
          </div>

         <p>Em Construção!</p>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal treinamento -->

        <div id="cadastreseModal" class="reveal-modal" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Cadastre-se Conosco</h2>
          </div>

          <form id="formularioCadastro">

            <div class="row">
              <div class="large-12 columns">
                <label for="inputNomeRazao">Nome / Razão Social
                  <input type="text" id="inputNomeRazao" placeholder="Escreva o seu nome ou razão social" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <label for="inputRespContato">Responsável / Contato
                  <input type="text" id="inputRespContato" placeholder="Escreva o seu nome ou razão social" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-6 columns">
                <label for="inputCpfCnpj">CPF / CNPJ
                  <input type="text" id="inputCpfCnpj" placeholder="Escreva o seu cpf ou cnpj" />
                </label>
              </div>
              <div class="large-6 columns">
                <label for="inputInscSusep">N.° INSC. SUSEP
                  <input type="text" id="inputCpfCnpj" placeholder="Escreva o seu número de inscrição no SUSEP" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <label for="inputEndereco">Endereco
                  <input type="text" id="inputEndereco" placeholder="Escreva o seu endereço" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-6 columns">
                <label for="inputBairro">Bairro
                  <input type="text" id="inputBairro" placeholder="Escreva o seu bairro" />
                </label>
              </div>
              <div class="large-6 columns">
                <label for="inputCidade">Cidade
                  <input type="text" id="inputCidade" placeholder="Escreva a sua cidade" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-6 columns">
                <label for="inputUf">Estado
                  <select>
                    <option value="">Selecione</option>
                    <option value="AC">Acre</option>
                    <option value="AL">Alagoas</option>
                    <option value="AP">Amapá</option>
                    <option value="AM">Amazonas</option>
                    <option value="BA">Bahia</option>
                    <option value="CE">Ceará</option>
                    <option value="DF">Distrito Federal</option>
                    <option value="ES">Espirito Santo</option>
                    <option value="GO">Goiás</option>
                    <option value="MA">Maranhão</option>
                    <option value="MS">Mato Grosso do Sul</option>
                    <option value="MT">Mato Grosso</option>
                    <option value="MG">Minas Gerais</option>
                    <option value="PA">Pará</option>
                    <option value="PB">Paraíba</option>
                    <option value="PR">Paraná</option>
                    <option value="PE">Pernambuco</option>
                    <option value="PI">Piauí</option>
                    <option value="RJ">Rio de Janeiro</option>
                    <option value="RN">Rio Grande do Norte</option>
                    <option value="RS">Rio Grande do Sul</option>
                    <option value="RO">Rondônia</option>
                    <option value="RR">Roraima</option>
                    <option value="SC">Santa Catarina</option>
                    <option value="SP">São Paulo</option>
                    <option value="SE">Sergipe</option>
                    <option value="TO">Tocantins</option>
                  </select>
                </label>
              </div>
              <div class="large-6 columns">
                <label for="inputCep">CEP
                  <input type="text" id="inputCep" placeholder="Escreva o seu CEP" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-6 columns">
                <label for="inputTelefone">Telefone
                  <input type="text" id="inputTelefone" placeholder="Escreva o seu telefone" />
                </label>
              </div>
              <div class="large-6 columns">
                <label for="inputCelular">Celular
                  <input type="text" id="inputCelular" placeholder="Escreva o seu celular" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-6 columns">
                <label for="inputFax">Fax
                  <input type="text" id="inputFax" placeholder="Escreva o seu fax" />
                </label>
              </div>
              <div class="large-6 columns">
                <label for="inputEmail">E-mail
                  <input type="text" id="inputEmail" placeholder="Escreva o seu email" />
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <label for="textObservacoes">Observações
                  <textarea id="textObservacoes" placeholder="Caso queira comentar algo, utilize este espaço"></textarea>
                </label>
              </div>
            </div>

            <div class="row">
              <div class="large-12 columns">
                <input class="button expand" type="submit" value="Cadastrar-se">
              </div>
            </div>
          </form>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal treinamento -->

        <div id="sugestoesModal" class="reveal-modal" data-reveal>
          <div class="fundo_titulo_modal_2">
            <div class="circle">
              
            </div>
            <div class="linha_vertical">
              
            </div>
            <div class="linha_horizontal">
              
            </div>
            <h2 class="titulo_modal">Sugestões e Reclamações</h2>
          </div>

          <p>Visando a melhoria continua de nossos serviços e a consequente satisfação dos nossos Corretores de Seguros, solicitamos que deixe seu comentário, pois sua opinião é muito importante Futura União.</p>

         <p>Em Construção!</p>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal treinamento -->

        <div id="missaoModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Missão</h2>
          </div>

         <p>Oferecer uma prestação de serviços de qualidade e diferenciada no
segmento de Assessoria Exclusiva à corretores de seguros</p>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal missao -->

        <div id="valoresModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Valores</h2>
          </div>

         <p>Profissionais capacitados e especializados que possuem vasta
experiência nas diversas áreas da Companhia; Valorização do trabalho de
nossos colaboradores; Segurança nos negócios; Objetividade e transparência
na relação com os corretores e seguradora.</p>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal valores -->

        <div id="empresaModal" class="reveal-modal" data-reveal>

          <div class="fundo_titulo_modal">
            <h2 class="titulo_modal">Sobre a Empresa</h2>
          </div>

          <article>
            <blockquote class="bq_empresa">" As coisas mudam, as pessoas não... "
            </blockquote>
            
            <p class="subtitulo_empresa">Amigo corretor(a).
</p>
            
            <div class="texto_empresa">
              <p>Durante 18 anos, tive o privilégio de fazer parte da equipe de colaboradores da
SulAmérica Seguros.</p>
              <p>Neste período que é praticamente metade da minha vida, foi repleto de
aprendizados e realizações e posso dizer que de certa forma, ajudei a
assegurar o patrimônio e o bem estar de milhares de empresas e pessoas.</p>
              <p>É com orgulho que vejo minha participação no desenvolvimento e crescimento
desta empresa, que sempre me mostrou que trabalhando com seriedade,
determinação e honestidade o sucesso é certo.</p>
              <p>Outro grande aprendizado que tive, é que não podemos nunca parar de crescer
e de aceitarmos desafios, e baseado neste ensinamento, que no ano de 2009
nasceu a <strong>“Futura União – Assessoria e Consultoria Exclusiva da
SulAmérica”</strong>, uma empresa voltada ao atendimento <strong>EXCLUSIVO</strong> à corretores
de seguros com foco no varejo, aonde poderei utilizar todo o conhecimento que
adquiri do mercado segurador e também poder auxiliar e facilitar a
comercialização dos produtos da <strong>SULAMÉRICA</strong>.
</p>
              <p>Estamos sempre atentos as necessidades e oportunidades do mercado e
também na constante busca de atender cada vez melhor e de forma completa
nossos parceiros e clientes.</p>
              <p>Aproveito a oportunidade para convidá-lo a visitar nossas instalações e
firmarmos a nossa <strong>FUTURA UNIÃO</strong>.</p>

            </div>
          </article>

          <a class="close-reveal-modal">&#215;</a>
        </div> <!-- fim modal valores -->

        <!-- fim das janelas modais  -->



        
      </div>
        <?php echo $this->inlineScript() ?>


      
            <script>
        $.ajaxPrefilter( "json script", function( options ) {
          options.crossDomain = true;
        });

        window.onload = function() {
            // Listen to the double click event.
            if ( window.addEventListener )
                document.body.addEventListener( 'dblclick', onDoubleClick, false );
            else if ( window.attachEvent )
                document.body.attachEvent( 'ondblclick', onDoubleClick );

        };

        function onDoubleClick( ev ) {
            // Get the element which fired the event. This is not necessarily the
            // element to which the event has been attached.
            var element = ev.target || ev.srcElement;

            // Find out the div that holds this element.
            var name;

            do {
                element = element.parentNode;
            }
            while ( element && ( name = element.nodeName.toLowerCase() ) &&
                ( name != 'div' || element.className.indexOf( 'editable' ) == -1 ) && name != 'body' );

            if ( name == 'div' && element.className.indexOf( 'editable' ) != -1 )
                replaceDiv( element );
        }

        var editor;

        function replaceDiv( div ) {
            if ( editor )
                editor.destroy();

            editor = CKEDITOR.replace( div );
        }

        $.fn.accordion.defaults.container = false; 

        $(document).ready(function () {
          
          $(document).foundation();

          $(".menu-accordion h3").click(function(){
          
            $(".menu-accordion ul ul").slideUp();
            
            if(!$(this).next().is(":visible")) {
              $(this).next().slideDown();
            
            }
          });

          $(".menu-accordion ul ul li").click(function(){
            $(".active").removeClass("active").addClass("inactive");
            $(this).removeClass("inactive").addClass("active");
          });

          $("#sitemap").accordion();

        });

      </script>

      <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] +
':35729/livereload.js?snipver=2"></' + 'script>')</script>

    </body>
</html>
