<div class="row">
	<div class="large-12 small-12 columns">

		

		<div class="form-login">
			<div class="row">
				<div class="large-4 small-12 large-centered columns">
					<h3 class="title-pagina">Login</h3>
					<?php if($this->error): ?>
					<p>Usuário ou senha inválidos</p>
					<?php endif; ?>

					<?php

					$form = $this->form;
					$form->setAttribute('action',$this->url('cms-auth'));
					$form->prepare();

					echo $this->form()->openTag($form);
					echo $this->formCollection($form);
					echo $this->form()->closeTag();

					?>
				</div>
			</div>
		</div>

	</div>
</div>