<div id="home_index">
	<div id="fundo_banner_home" class="texto_centralizado">
		<img id="banner_futura_uniao" src="/img/banner-futura.png" alt="Banner Futura Uniao">
	</div>
	
	<div id="chamada_sulamerica">
		<div class="large-8 columns texto_centralizado">
			<p id="texto_sulamerica" class="light_right_border">Somos uma <strong>consultoria exclusiva SulAmérica</strong>. Aqui você pode receber todo apoio para sua venda! Fale conosco!</p>
		</div>
		<div class="large-4 columns">
			<img id="logo_sulamerica" src="/img/logo-sulamerica-novo.png" alt="Logo da SulAmerica">
		</div>
	</div>
	
	<div id="futurauniao_features">
		<div class="texto_centralizado">
			<h1>Confira as vantagens para você corretor:</h1>
		</div>
		<div class="large-4 columns texto_centralizado">
			<h2>Serviços</h2>
			<div class="campo_img">
				<img src="/img/servicos.png" alt="Imagem Servicos">
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente aspernatur ad, sint tempore eveniet, itaque.</p>
			<button>SAIBA MAIS</button>
		</div>
		<div class="large-4 columns texto_centralizado">
			<h2>Produtos</h2>
			<div class="campo_img">
				<img src="/img/produtos.png" alt="Imagem Produtos">
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente aspernatur ad, sint tempore eveniet, itaque.</p>
			<button>SAIBA MAIS</button>
		</div>
		<div class="large-4 columns texto_centralizado">
			<h2>Para Corretores</h2>
			<div class="campo_img">
				<img src="/img/para-corretores.png" alt="Imagem Para Corretores">
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente aspernatur ad, sint tempore eveniet, itaque.</p>
			<button>SAIBA MAIS</button>
		</div>
	</div>
</div>

<div style="clear:both;">