<div id="home_index">
	<div id="fundo_banner_home" class="texto_centralizado">
		<img id="banner_futura_uniao" src="/img/banner-futura.png" alt="Banner Futura Uniao">
	</div>
	
	<div id="chamada_sulamerica">
		<div class="large-8 columns texto_centralizado">
			<p id="texto_sulamerica" class="light_right_border">Somos uma <strong>consultoria exclusiva SulAmérica</strong>. Aqui você pode receber todo apoio para sua venda! Fale conosco!</p>
		</div>
		<div class="large-4 columns">
			<img id="logo_sulamerica" src="/img/logo-sulamerica-novo.png" alt="Logo da SulAmerica">
		</div>
	</div>
	
	<div id="futurauniao_features">
		<div class="texto_centralizado">
			<h1>Confira as vantagens para você corretor:</h1>
		</div>
		<div class="large-4 columns texto_centralizado">
			<h2>Missão</h2>
			<div class="campo_img">
				<img src="/img/servicos.png" alt="Imagem Servicos">
			</div>
			<p>Oferecer uma prestação de serviços de qualidade e diferenciada no
segmento...</p>
			<button><a href="" data-reveal-id="missaoModal">SAIBA MAIS</a></button>
		</div>
		<div class="large-4 columns texto_centralizado">
			<h2>Valores</h2>
			<div class="campo_img">
				<img src="/img/produtos.png" alt="Imagem Produtos">
			</div>
			<p>Profissionais capacitados e especializados que possuem vasta
experiência...</p>
			<button><a href="" data-reveal-id="valoresModal">SAIBA MAIS</a></button>
		</div>
		<div class="large-4 columns texto_centralizado">
			<h2>Sobre a Empresa</h2>
			<div class="campo_img">
				<img src="/img/para-corretores.png" alt="Imagem Para Corretores">
			</div>
			<p>Durante 18 anos, tive o privilégio de fazer parte da equipe de colaboradores...</p>
			<button><a href="" data-reveal-id="empresaModal">SAIBA MAIS</a></button>
		</div>
	</div>
</div>

<div style="clear:both;">